### ISSUE TITLE
First link in the getting started section of the readme page is a 404

### ISSUE THREAD

**Issue by renatoparedes** [harvard-vpal/adaptive-engine#40]
Hello,

The following link from the readme page is a 404:

Python engine library folder and documentation
(https://github.com/harvard-vpal/adaptive-engine/tree/master/alosi)

Could someone update this with the latest working link please?

Cheers,

Renato

**Comment by kunanit** [comment]
Thanks for raising the issue! The outdated link was left over from when the alosi library was migrated out to its own repo. The replacement link is already in the related projects section (https://github.com/harvard-vpal/alosi).
